import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';

// This will boot up your Telegram bot in the background of the Express server
import './scripts/telegram_bot.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 10000;

// Serve the static files from the React app (the 'dist' folder generated by Vite)
app.use(express.static(path.join(__dirname, 'dist')));

// Also serve the 'public' folder directly so the bot can mutate data.json and the frontend can fetch it
app.use(express.static(path.join(__dirname, 'public')));

// Any request that doesn't match a static file gets routed back to React's index.html
app.get('*', (req, res) => {
    const indexHtml = path.join(__dirname, 'dist', 'index.html');
    if (fs.existsSync(indexHtml)) {
        res.sendFile(indexHtml);
    } else {
        res.status(404).send('Not Found. Make sure to run `npm run build` before starting the server.');
    }
});

app.listen(PORT, () => {
    console.log(`🚀 Production Express server running on port ${PORT}`);
});
