-- Migration: Create companions table
CREATE TABLE public.companions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER,
    location TEXT,
    price TEXT,
    description TEXT,
    image_url TEXT,
    rating NUMERIC(3, 1) DEFAULT 0.0,
    reviews INTEGER DEFAULT 0,
    availability TEXT,
    tags JSONB DEFAULT '[]'::jsonb,
    metrics JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Basic RLS Policies
ALTER TABLE public.companions ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Public profiles are viewable by everyone." 
ON public.companions FOR SELECT 
USING (true);

-- Allow authenticated users to insert/update (To be refined later for admin only)
CREATE POLICY "Authenticated users can insert profiles." 
ON public.companions FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Authenticated users can update profiles." 
ON public.companions FOR UPDATE 
TO authenticated 
USING (true);
